/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  safelist: [
    // Ensure commonly used classes are always included
    'bg-gray-50',
    'bg-white',
    'bg-gray-100',
    'bg-green-50',
    'bg-emerald-600',
    'text-gray-900',
    'text-gray-600',
    'text-gray-500',
    'text-emerald-600',
    'text-green-800',
    'text-green-700',
    'text-green-600',
    'p-6',
    'p-8',
    'p-4',
    'p-3',
    'p-2',
    'mb-4',
    'mb-6',
    'mb-8',
    'mb-2',
    'mt-4',
    'space-x-3',
    'space-x-1',
    'space-y-3',
    'rounded-2xl',
    'rounded-lg',
    'rounded-xl',
    'rounded-full',
    'shadow-md',
    'shadow-lg',
    'border-gray-100',
    'border-gray-200',
    'hover:shadow-lg',
    'hover:scale-105',
    'transition-all',
    'duration-200',
    'w-6',
    'h-6',
    'w-5',
    'h-5',
    'w-4',
    'h-4',
    'w-3',
    'h-3',
    'w-12',
    'h-12',
    'text-lg',
    'text-sm',
    'text-xs',
    'text-3xl',
    'font-semibold',
    'font-bold',
    'font-medium',
    'max-w-4xl',
    'grid',
    'md:grid-cols-2',
    'lg:grid-cols-2',
    'gap-6',
    'gap-8',
    'col-span-2',
  ],
  theme: {
    extend: {
      colors: {
        emerald: {
          600: '#059669',
          700: '#047857',
        },
        primary: {
          600: '#059669',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
